####################################
############ Initial setup #########
####################################

# Setting the gas pressure at 1 bar
/DMPX/geometry/SetGasPressure 1. bar


# The HeedDeltaElectron model simulates the transport and ionization of low-energy electrons and photons. It does take into account Coulomb scattering.
# For electrons, this model should not be triggered for energies above a few tens of keV, if not the simulated energy deposition by the primary particle will be off.
# The energies for the gasModelParameters are in keV
/gasModelParameters/heed/heeddeltaelectron/addparticle e- 0. 0.001
/gasModelParameters/heed/heeddeltaelectron/addparticle gamma 10. 1000000.


# The HeedNewTrack model simulates high energy charged particles in relatively thin gas absorbers as it does not take into account Coulomb scattering
# (The energies are in keV)
/gasModelParameters/heed/heednewtrack/addparticle e- 0.1 1000.
/gasModelParameters/heed/heednewtrack/addparticle proton 40. 1000.


# Setting the gasModelParameters 
/gasModelParameters/heed/drift 0
/gasModelParameters/heed/driftRKF 0
/gasModelParameters/heed/trackmicroscopic 0
/gasModelParameters/heed/createAval 1
/gasModelParameters/heed/visualizechamber 1
/gasModelParameters/heed/visualizesignals 1
/gasModelParameters/heed/visualizefield 1
/gasModelParameters/heed/voltageplanehv -100
/gasModelParameters/heed/voltageplanelow 0
/gasModelParameters/heed/voltageanodewire 1500.
/gasModelParameters/heed/voltagecathodewire 0.
/gasModelParameters/heed/voltagegate -70.
/gasModelParameters/heed/voltagedeltagate 90.

/run/numberOfThreads 1
/control/cout/ignoreThreadsExcept 0
/DMPX/phys/setLowLimitE 0.001 eV
/DMPX/phys/InitializePhysics emlivermore
/DMPX/phys/AddParametrisation
/process/em/AddPAIRegion all GasRegion PAIphoton

# Setting the seed and initializing the run
#/random/setSeeds 0 0
/run/initialize

####################################
############ Verbosities ###########
####################################

/tracking/verbose 0
/run/verbose 1
/event/verbose 1
/vis/verbose 6

####################################
########### Visualization ##########
####################################

/vis/open OGL 600x600-0+0
/vis/drawVolume
/vis/scene/add/axes 0 0 0 10 cm

/vis/scene/add/trajectories smooth
/vis/scene/add/hits

# Gamma rays appear in yellow
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow


# When running an event, accumulate N events (in this case, up to 100) for visualization
/vis/scene/endOfEventAction accumulate 100

# The particles are shot from a rectangular plane situated at the position of the slit, in the positive z direction
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre -21. 0.9 102.27 mm
/gps/pos/halfx 10 mm
/gps/pos/halfy 2.0 mm

# To see where the GPS is
/vis/scene/add/gps

# Energy and direction of the particles being shot
/gps/direction 0. 0. -1.
/gps/particle gamma
/gps/energy 70 keV









