####################################
############ Initial setup #########
####################################

# Setting the gas pressure at 1 bar
/DMPX/geometry/SetGasPressure 1. bar

# The HeedDeltaElectron model simulates the transport and ionization of low-energy electrons and photons
/gasModelParameters/heed/heeddeltaelectron/addparticle e- 0.001 100 keV
/gasModelParameters/heed/heeddeltaelectron/addparticle gamma 3 30 keV

# The HeedNewTrack model simulates the primary ionization caused by charged particles entering a gas volume.
/gasModelParameters/heed/heednewtrack/addparticle e-  0.001 30 keV

# Setting the gasModelParameters 
/gasModelParameters/heed/drift 0
/gasModelParameters/heed/driftRKF 1
/gasModelParameters/heed/trackmicroscopic 0
/gasModelParameters/heed/createAval 1
/gasModelParameters/heed/visualizechamber 1
/gasModelParameters/heed/visualizesignals 0
/gasModelParameters/heed/visualizefield 1
#/gasModelParameters/heed/voltageplanehv -100
#/gasModelParameters/heed/voltageplanelow 0
#/gasModelParameters/heed/voltageanodewire 1500.
#/gasModelParameters/heed/voltagecathodewire 0.
#/gasModelParameters/heed/voltagegate -70.
#/gasModelParameters/heed/voltagedeltagate 90.

/run/numberOfThreads 1
/control/cout/ignoreThreadsExcept 0
/DMPX/phys/setLowLimitE 1 eV
/DMPX/phys/InitializePhysics emlivermore
/DMPX/phys/AddParametrisation
/process/em/AddPAIRegion all GasRegion PAIphoton

/run/initialize

####################################
############ Verbosities ###########
####################################

/tracking/verbose 0
/run/verbose 1
/event/verbose 1
/vis/verbose 6

####################################
########### Visualization ##########
####################################

/vis/open OGL 600x600-0+0
/vis/drawVolume
/vis/scene/add/axes 0 0 0 10 cm

/vis/scene/add/trajectories smooth
/vis/scene/add/hits

/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/set +0 yellow
/vis/modeling/trajectories/drawByCharge-1/set -1 red

# When running an event, accumulate N events (in this case, up to 100) for visualization
/vis/scene/endOfEventAction accumulate 100

# The particles are shot from a rectangular plane situated at the position of the slit, in the positive z direction
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre -21. 0.9 102.27 mm
/gps/pos/halfx 10 mm
/gps/pos/halfy 2.0 mm

/gps/direction 0. 0. -1.
/gps/particle gamma
/gps/ene/type Mono
/gps/ene/mono 30 keV









