########################
##### GAS PRESSURE #####
########################

    /DMPX/geometry/SetGasPressure 1. bar

##########################################
##### PARAMETERS FOR DEGRAD AND HEED #####
##########################################
 
    # Thermal energy for the DegradModel. Below this energy, the HeedDeltaElectronModel will be activated
    /gasModelParameters/degrad/thermalenergy 10. eV

    # Adding the energy ranges in keV for which the HeedDeltaElectronModel will be activated
    /gasModelParameters/heed/heeddeltaelectron/addparticle e- 0.001 100
    /gasModelParameters/heed/heeddeltaelectron/addparticle gamma 0.1 1000

    # In this simulation, we are using Kr for the detection gas and CH4 for the extinction gas
    /gasModelParameters/degrad/numberofgases 2

    # Please, input the gas identifier for Degrad (search for "GAS NUMBER" in the Degrad source code)
    /gasModelParameters/degrad/setGasList 6 8 0 0 0 0
    /gasModelParameters/degrad/setGasPercentages 90.0 10.0 0.0 0.0 0.0 0.0
    /gasModelParameters/degrad/temperature 293.15 K
    /gasModelParameters/degrad/distanceanodecathodes 10. mm
    
    /gasModelParameters/heed/gasfile ar_93_co2_7.gas
    /gasModelParameters/heed/drift 1
    /gasModelParameters/heed/driftRKF 0
    /gasModelParameters/heed/trackmicroscopic 1
    /gasModelParameters/heed/createAval 0
    /gasModelParameters/heed/visualizechamber 1
    /gasModelParameters/heed/visualizesignals 1
    /gasModelParameters/heed/visualizefield 1
    /gasModelParameters/heed/voltageanodewire 1500.    # [V]
    /gasModelParameters/heed/voltagecathodeplane 0.     # [V]


####################################################
##### OUTPUT, MODEL AND ENERGY PARAMETRISATION #####
####################################################

    /run/numberOfThreads 1 # Since Heed is not yet multi-thread safe, we must put 1 here
    /control/cout/ignoreThreadsExcept 0
    #/control/cout/setCoutFile output.dmp

    # Below the energy set in "setLowLimitE", the particles will no longer be tracked. 
    # They will either exit the volume, or give their energy to another particle, that 
    # will just store it, after a collision.
    /DMPX/phys/setLowLimitE 1. eV 
    /DMPX/phys/InitializePhysics emlivermore
    /DMPX/phys/AddParametrisation
    /process/em/AddPAIRegion all GasAndAnodesRegion PAIphoton

    #/random/setSeeds 0 0
    /run/initialize

    #/param/InActivateModel DegradModel
    #/param/InActivateModel HeedDeltaElectronModel

    /analysis/setFileName output.root

####################################
############ Verbosities ###########
####################################
    
    /tracking/verbose 1
    /run/verbose 1
    /event/verbose 1
    /vis/verbose 1

####################################
########### Visualization ##########
####################################

    # Different visualization options. Choose based on installed drivers and visualization purposes.
    #/vis/open VRML2FILE
    /vis/open OGL 600x600-0+0
    #/vis/open OGLSX

    # Draw geometry:
    /vis/drawVolume
    /vis/scene/add/trajectories smooth
    /vis/scene/add/hits
    /vis/viewer/set/lightsThetaPhi 90. 0. # In degrees
    /vis/viewer/set/viewpointThetaPhi 50. 30. # In degrees
    /vis/viewer/set/style surface
    /vis/viewer/set/hiddenEdge true
    /vis/scene/add/axes 0 0 0 3 cm


###################################
###### PLOTTING TRAJECTORIES ######
###################################

    # Draw smooth trajectories at end of event.
    # Gamma-rays represented in green, electrons in red.

    # For plotting depending on the name of the particle
    #/vis/modeling/trajectories/create/drawByParticleID
    #/vis/modeling/trajectories/drawByParticleID-0/set e- green
    #/vis/modeling/trajectories/drawByParticleID-0/verbose 1

    # Filter for onbserving only electrons (must be coupled with the charge filter)
    #/vis/filtering/trajectories/create/particleFilter
    #/vis/filtering/trajectories/particleFilter-0/add e-

    # For plotitng following the charge of the particle
    /vis/modeling/trajectories/create/drawByCharge drawByCharge-0
    /vis/modeling/trajectories/drawByCharge-0/set 0 green
    /vis/modeling/trajectories/drawByCharge-0/set -1 red
    /vis/modeling/trajectories/drawByCharge-0/verbose 1
    /vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
    /vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 6

    /vis/scene/endOfEventAction accumulate 100

    /tracking/storeTrajectory 1

#########################################
##### GENERAL PARTICLE SOURCE (GPS) #####
#########################################

    # The particles are shot from a rectangular plane situated at the position of the slit, 
    # in the positive z direction
    /gps/pos/type Plane
    /gps/pos/shape Rectangle

    # The height in the y direction will be used for the calculation of the electric field
    /gps/pos/centre -21. 102.27 2.9 mm

    # By default, the plane would be in the XY plane. However, we want it to be in the XZ plane, Since
    # Garfield++ can only define the wires following the Z direction. Thus, it is necessary to apply 
    # a rotation. The default rot1 vector is following the X axis (1 0 0), and the default rot2 
    # vector follows (0 0 1). The resulting vector for the plane will be in the direction perpendicular
    # to both rot1 and rot2, i.e. (0 1 0)
    /gps/pos/rot2 0 0 1 

    # The entry slit is around 30 mm long and 2 mm wide (remember, it is in the XZ plane)
    /gps/pos/halfx 15. mm 
    /gps/pos/halfz 0.01 mm # Setting a minimal width for the entry slit, so Geant4 does not crash
    /gps/pos/halfy 1.5 mm # Careful: y is z here!

    # To see where the GPS is
    /vis/scene/add/gps

    # If we want the photons to be following a given fixed direction, we can uncomment the 
    # following line (and therefore comment the commands with"/gps/ang")
    #/gps/direction 0. -1. 0.

    # The particles will be isotropically shot along the angles we precise
    /gps/ang/type iso 

    # In order for theta and phi to behave as usual in the spherical coordinates, we must correct
    # the rotation applied to the plane, so the angles are not rotated in the same way.
    /gps/ang/rot2 0 1 0 

    # Some useful directions:
    # Direction parallel to the y axis ->  theta = 90. deg, phi = 180 deg.
    # Direction parallel to the z axis -> theta = 0. deg., for all phi
    # All angles are in degrees
    /gps/ang/mintheta 90. deg # Theta is fixed such that the particles are shot in the XY plane
    /gps/ang/maxtheta 90. deg
    /gps/ang/minphi 70. deg 
    /gps/ang/maxphi 110. deg

    # Monoenergetic photon particle source at a given energy
    /gps/particle gamma
    /gps/ene/type Mono
    /gps/ene/mono 10. keV

